%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'hdnwr_nl';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_mu'};
M_.exo_names_tex(1) = {'\varepsilon^{\mu}'};
M_.exo_names_long(1) = {'monetary policy innovation'};
M_.exo_names(2) = {'eps_a'};
M_.exo_names_tex(2) = {'\varepsilon^{a}'};
M_.exo_names_long(2) = {'technology innovation'};
M_.endo_names = cell(10,1);
M_.endo_names_tex = cell(10,1);
M_.endo_names_long = cell(10,1);
M_.endo_names(1) = {'jstar'};
M_.endo_names_tex(1) = {'j^{*}'};
M_.endo_names_long(1) = {'cutoff variety'};
M_.endo_names(2) = {'y'};
M_.endo_names_tex(2) = {'y'};
M_.endo_names_long(2) = {'output'};
M_.endo_names(3) = {'h'};
M_.endo_names_tex(3) = {'h'};
M_.endo_names_long(3) = {'aggregate labor'};
M_.endo_names(4) = {'u'};
M_.endo_names_tex(4) = {'u'};
M_.endo_names_long(4) = {'unemployment rate'};
M_.endo_names(5) = {'w'};
M_.endo_names_tex(5) = {'w'};
M_.endo_names_long(5) = {'real wage'};
M_.endo_names(6) = {'ii'};
M_.endo_names_tex(6) = {'i'};
M_.endo_names_long(6) = {'nominal interest rate'};
M_.endo_names(7) = {'pi'};
M_.endo_names_tex(7) = {'\pi'};
M_.endo_names_long(7) = {'price inflation'};
M_.endo_names(8) = {'piW'};
M_.endo_names_tex(8) = {'\pi^{W}'};
M_.endo_names_long(8) = {'wage inflation'};
M_.endo_names(9) = {'mu'};
M_.endo_names_tex(9) = {'\mu'};
M_.endo_names_long(9) = {'monetary policy shock'};
M_.endo_names(10) = {'a'};
M_.endo_names_tex(10) = {'a'};
M_.endo_names_long(10) = {'technology shock'};
M_.endo_partitions = struct();
M_.param_names = cell(14,1);
M_.param_names_tex = cell(14,1);
M_.param_names_long = cell(14,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'sig'};
M_.param_names_tex(2) = {'sig'};
M_.param_names_long(2) = {'sig'};
M_.param_names(3) = {'theta'};
M_.param_names_tex(3) = {'theta'};
M_.param_names_long(3) = {'theta'};
M_.param_names(4) = {'alpha'};
M_.param_names_tex(4) = {'alpha'};
M_.param_names_long(4) = {'alpha'};
M_.param_names(5) = {'eta'};
M_.param_names_tex(5) = {'eta'};
M_.param_names_long(5) = {'eta'};
M_.param_names(6) = {'Gam0'};
M_.param_names_tex(6) = {'Gam0'};
M_.param_names_long(6) = {'Gam0'};
M_.param_names(7) = {'Gam1'};
M_.param_names_tex(7) = {'Gam1'};
M_.param_names_long(7) = {'Gam1'};
M_.param_names(8) = {'del'};
M_.param_names_tex(8) = {'del'};
M_.param_names_long(8) = {'del'};
M_.param_names(9) = {'pistar'};
M_.param_names_tex(9) = {'pistar'};
M_.param_names_long(9) = {'pistar'};
M_.param_names(10) = {'un'};
M_.param_names_tex(10) = {'un'};
M_.param_names_long(10) = {'un'};
M_.param_names(11) = {'alpha_pi'};
M_.param_names_tex(11) = {'alpha\_pi'};
M_.param_names_long(11) = {'alpha_pi'};
M_.param_names(12) = {'alpha_y'};
M_.param_names_tex(12) = {'alpha\_y'};
M_.param_names_long(12) = {'alpha_y'};
M_.param_names(13) = {'rho_mu'};
M_.param_names_tex(13) = {'rho\_mu'};
M_.param_names_long(13) = {'rho_mu'};
M_.param_names(14) = {'rho_a'};
M_.param_names_tex(14) = {'rho\_a'};
M_.param_names_long(14) = {'rho_a'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 10;
M_.param_nbr = 14;
M_.orig_endo_nbr = 10;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [1 2 3 4 5 6 7 8 9 10];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 10;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 4 0;
 0 5 14;
 0 6 0;
 0 7 0;
 1 8 0;
 0 9 0;
 0 10 15;
 0 11 0;
 2 12 0;
 3 13 0;]';
M_.nstatic = 5;
M_.nfwrd   = 2;
M_.npred   = 3;
M_.nboth   = 0;
M_.nsfwrd   = 2;
M_.nspred   = 3;
M_.ndynamic   = 5;
M_.dynamic_tmp_nbr = [21; 22; 4; 0; ];
M_.equations_tags = {
  1 , 'name' , 'y' ;
  2 , 'name' , '2' ;
  3 , 'name' , '3' ;
  4 , 'name' , '4' ;
  5 , 'name' , '5' ;
  6 , 'name' , '6' ;
  7 , 'name' , '7' ;
  8 , 'name' , 'u' ;
  9 , 'name' , '9' ;
  10 , 'name' , '10' ;
};
M_.mapping.jstar.eqidx = [6 7 8 ];
M_.mapping.y.eqidx = [1 2 4 6 ];
M_.mapping.h.eqidx = [1 3 6 ];
M_.mapping.u.eqidx = [8 ];
M_.mapping.w.eqidx = [3 5 6 ];
M_.mapping.ii.eqidx = [2 4 ];
M_.mapping.pi.eqidx = [2 4 5 6 ];
M_.mapping.piW.eqidx = [5 6 7 ];
M_.mapping.mu.eqidx = [4 9 ];
M_.mapping.a.eqidx = [1 3 10 ];
M_.mapping.eps_mu.eqidx = [9 ];
M_.mapping.eps_a.eqidx = [10 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 3;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 9];
M_.block_structure.block(1).variable = [ 9];
M_.block_structure.block(1).is_linear = false;
M_.block_structure.block(1).NNZDerivatives = 2;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(2).Simulation_Type = 3;
M_.block_structure.block(2).endo_nbr = 1;
M_.block_structure.block(2).mfs = 1;
M_.block_structure.block(2).equation = [ 10];
M_.block_structure.block(2).variable = [ 10];
M_.block_structure.block(2).is_linear = false;
M_.block_structure.block(2).NNZDerivatives = 2;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(3).Simulation_Type = 8;
M_.block_structure.block(3).endo_nbr = 7;
M_.block_structure.block(3).mfs = 7;
M_.block_structure.block(3).equation = [ 4 5 7 1 3 6 2];
M_.block_structure.block(3).variable = [ 6 8 1 3 5 7 2];
M_.block_structure.block(3).is_linear = false;
M_.block_structure.block(3).NNZDerivatives = 23;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [5 8 9 10 11 12 13 14 20 21 ];
M_.block_structure.block(4).Simulation_Type = 1;
M_.block_structure.block(4).endo_nbr = 1;
M_.block_structure.block(4).mfs = 1;
M_.block_structure.block(4).equation = [ 8];
M_.block_structure.block(4).variable = [ 4];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).NNZDerivatives = 1;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([2 6 1 7 2 3 6 3 6 4 5 6 2 5 1 2 6 1 4 6 7 7 7 ]);
M_.block_structure.block(3).g1_sparse_colval = int32([5 5 8 8 9 9 9 10 10 11 11 11 12 12 13 13 13 14 14 14 14 20 21 ]);
M_.block_structure.block(3).g1_sparse_colptr = int32([1 1 1 1 1 3 3 3 5 8 10 13 15 18 22 22 22 22 22 22 23 24 ]);
M_.block_structure.block(4).g1_sparse_rowval = int32([]);
M_.block_structure.block(4).g1_sparse_colval = int32([]);
M_.block_structure.block(4).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 9 10 6 8 1 3 5 7 2 4];
M_.block_structure.equation_reordered = [ 9 10 4 5 7 1 3 6 2 8];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 5 5;
 6 5;
 9 9;
 10 10;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 2;
 1 3;
 1 10;
 2 2;
 2 6;
 3 3;
 3 5;
 3 10;
 4 2;
 4 6;
 4 7;
 4 9;
 5 5;
 5 7;
 5 8;
 6 1;
 6 2;
 6 3;
 6 7;
 6 8;
 7 1;
 7 8;
 8 1;
 8 4;
 9 9;
 10 10;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 2 2;
 2 7;
];
M_.block_structure.dyn_tmp_nbr = 14;
M_.state_var = [9 10 5 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(10, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(14, 1);
M_.endo_trends = struct('deflator', cell(10, 1), 'log_deflator', cell(10, 1), 'growth_factor', cell(10, 1), 'log_growth_factor', cell(10, 1));
M_.NNZDerivatives = [34; 60; -1; ];
M_.dynamic_g1_sparse_rowval = int32([5 6 9 10 6 7 8 1 2 4 6 1 3 6 8 3 5 2 4 4 5 6 5 6 7 4 9 1 3 10 2 2 9 10 ]);
M_.dynamic_g1_sparse_colval = int32([5 5 9 10 11 11 11 12 12 12 12 13 13 13 14 15 15 16 16 17 17 17 18 18 18 19 19 20 20 20 22 27 31 32 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 1 1 1 3 3 3 3 4 5 8 12 15 16 18 20 23 26 28 31 31 32 32 32 32 32 33 33 33 33 34 35 ]);
M_.dynamic_g2_sparse_indices = int32([1 13 13 ;
1 13 20 ;
2 12 12 ;
2 22 22 ;
2 22 16 ;
2 22 27 ;
2 16 27 ;
2 27 27 ;
3 13 13 ;
3 13 20 ;
4 12 12 ;
4 12 17 ;
4 12 19 ;
4 17 17 ;
4 17 19 ;
5 5 5 ;
5 5 15 ;
5 5 17 ;
5 15 17 ;
6 11 11 ;
6 11 12 ;
6 11 13 ;
6 11 5 ;
6 11 17 ;
6 11 18 ;
6 12 12 ;
6 12 13 ;
6 12 18 ;
6 13 13 ;
6 13 18 ;
6 5 17 ;
6 17 17 ;
6 18 18 ;
7 11 11 ;
7 18 18 ;
8 11 11 ;
9 9 9 ;
9 19 19 ;
10 10 10 ;
10 20 20 ;
]);
M_.lhs = {
'y'; 
'y^(-sig)'; 
'a*alpha*h^(alpha-1)'; 
'1+ii'; 
'1+piW'; 
'y^sig*(h/(1-un)*((1+pistar)^del*(Gam0+Gam1*jstar)/(1+piW))^(-eta))^theta'; 
'(1+piW)^(1-eta)'; 
'u'; 
'log(mu)'; 
'log(a)'; 
};
M_.static_tmp_nbr = [18; 4; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 9];
M_.block_structure_stat.block(1).variable = [ 9];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 10];
M_.block_structure_stat.block(2).variable = [ 10];
M_.block_structure_stat.block(3).Simulation_Type = 6;
M_.block_structure_stat.block(3).endo_nbr = 7;
M_.block_structure_stat.block(3).mfs = 7;
M_.block_structure_stat.block(3).equation = [ 3 4 5 6 7 2 1];
M_.block_structure_stat.block(3).variable = [ 5 2 7 1 8 6 3];
M_.block_structure_stat.block(4).Simulation_Type = 1;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 8];
M_.block_structure_stat.block(4).variable = [ 4];
M_.block_structure_stat.variable_reordered = [ 9 10 5 2 7 1 8 6 3 4];
M_.block_structure_stat.equation_reordered = [ 9 10 3 4 5 6 7 2 1 8];
M_.block_structure_stat.incidence.sparse_IM = [
 1 2;
 1 3;
 1 10;
 2 2;
 2 6;
 2 7;
 3 3;
 3 5;
 3 10;
 4 2;
 4 6;
 4 7;
 4 9;
 5 7;
 5 8;
 6 1;
 6 2;
 6 3;
 6 5;
 6 7;
 6 8;
 7 1;
 7 8;
 8 1;
 8 4;
 9 9;
 10 10;
];
M_.block_structure_stat.tmp_nbr = 17;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 4 2 4 6 7 2 3 4 6 4 5 3 4 5 2 6 1 4 7 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 1 2 2 2 2 3 3 3 3 4 4 5 5 5 6 6 7 7 7 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 3 7 11 13 16 18 21 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([]);
M_.static_g1_sparse_rowval = int32([6 7 8 1 2 4 6 1 3 6 8 3 6 2 4 2 4 5 6 5 6 7 4 9 1 3 10 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 2 2 3 3 3 4 5 5 6 6 7 7 7 7 8 8 8 9 9 10 10 10 ]);
M_.static_g1_sparse_colptr = int32([1 4 8 11 12 14 16 20 23 25 28 ]);
M_.params(1) = 0.99;
beta = M_.params(1);
M_.params(2) = 1;
sig = M_.params(2);
M_.params(3) = 5;
theta = M_.params(3);
M_.params(4) = 0.75;
alpha = M_.params(4);
M_.params(5) = 11;
eta = M_.params(5);
M_.params(6) = 0.978;
Gam0 = M_.params(6);
M_.params(7) = 0.031;
Gam1 = M_.params(7);
M_.params(8) = 1;
del = M_.params(8);
M_.params(9) = 0.007417071777733097;
pistar = M_.params(9);
M_.params(10) = 0.04;
un = M_.params(10);
M_.params(11) = 1.5;
alpha_pi = M_.params(11);
M_.params(12) = 0.125;
alpha_y = M_.params(12);
M_.params(13) = 0.5;
rho_mu = M_.params(13);
M_.params(14) = 0.9;
rho_a = M_.params(14);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.0025)^2;
M_.Sigma_e(2, 2) = (0.01)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.nograph = true;
options_.order = 2;
options_.periods = 10000;
options_.pruning = true;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
fprintf('\n=== Steady-State Verification ===\n');
fprintf('jstar   = %.4f  (expected ~0.65)\n', oo_.steady_state(strmatch('jstar',M_.endo_names,'exact')));
fprintf('u       = %.4f  (expected ~0.06)\n', oo_.steady_state(strmatch('u',M_.endo_names,'exact')));
fprintf('h       = %.4f\n', oo_.steady_state(strmatch('h',M_.endo_names,'exact')));
fprintf('y       = %.4f\n', oo_.steady_state(strmatch('y',M_.endo_names,'exact')));
fprintf('w       = %.4f\n', oo_.steady_state(strmatch('w',M_.endo_names,'exact')));
fprintf('pi      = %.6f  (pistar = %.6f)\n', oo_.steady_state(strmatch('pi',M_.endo_names,'exact')), pistar);
fprintf('piW     = %.6f  (pistar = %.6f)\n', oo_.steady_state(strmatch('piW',M_.endo_names,'exact')), pistar);
fprintf('ii      = %.6f\n', oo_.steady_state(strmatch('ii',M_.endo_names,'exact')));
fprintf('1-jstar = %.4f  (expected ~0.35)\n', 1-oo_.steady_state(strmatch('jstar',M_.endo_names,'exact')));
fprintf('================================\n\n');


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'hdnwr_nl_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
